import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import Sidebar from "./components/sidebar";
import { Stack, ThemeProvider } from "@mui/material";
import "@fontsource/open-sauce-sans";
import Providers, { theme } from "./theme";
import ClientOnly from "./clientonly";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Alignly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <ClientOnly>
            <Stack direction='row'>
              <Sidebar />
              {children}
            </Stack>
          </ClientOnly>
        </Providers>
      </body>
    </html>
  );
}
